// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type InfoData struct {
	SubURL string
}

type osGuide struct {
	Name    string
	Clients []osClient
	Steps   []string
}

type osClient struct {
	Name string
	URL  string
}

func osGuides() []osGuide {
	return []osGuide{
		{
			Name: "Android",
			Clients: []osClient{
				{Name: "Happ (Google Play)", URL: "https://play.google.com/store/apps/details?id=com.happproxy"},
				{Name: "Hiddify-Next (GitHub)", URL: "https://github.com/hiddify/hiddify-next/releases"},
				{Name: "V2RayTun (Google Play)", URL: "https://play.google.com/store/apps/details?id=com.v2raytun.android"},
			},
			Steps: []string{
				"Установите один из клиентов выше",
				"Скопируйте ссылку подписки внизу страницы",
				"В клиенте: «Добавить подписку» → вставьте ссылку",
				"Нажмите кнопку подключения",
			},
		},
		{
			Name: "iOS",
			Clients: []osClient{
				{Name: "Happ (App Store)", URL: "https://apps.apple.com/app/happ-proxy-utility/id6504287215"},
				{Name: "V2RayTun (App Store)", URL: "https://apps.apple.com/app/v2raytun/id6476628951"},
				{Name: "Streisand (App Store)", URL: "https://apps.apple.com/app/streisand/id6450534064"},
			},
			Steps: []string{
				"Установите клиент",
				"Скопируйте ссылку подписки внизу страницы",
				"Импортируйте подписку — приложение запросит разрешение на VPN",
				"Подключитесь",
			},
		},
		{
			Name: "Windows",
			Clients: []osClient{
				{Name: "Hiddify Desktop", URL: "https://github.com/hiddify/hiddify-next/releases"},
				{Name: "NekoRay", URL: "https://github.com/MatsuriDayo/nekoray/releases"},
				{Name: "Invisible Man Xray", URL: "https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/releases"},
			},
			Steps: []string{
				"Скачайте и установите клиент",
				"Скопируйте ссылку подписки внизу страницы",
				"В клиенте: импорт подписки по URL",
				"Включите системный прокси / TUN-режим",
			},
		},
		{
			Name: "macOS",
			Clients: []osClient{
				{Name: "V2RayTun (Mac App Store)", URL: "https://apps.apple.com/app/v2raytun/id6476628951"},
				{Name: "Hiddify Desktop", URL: "https://github.com/hiddify/hiddify-next/releases"},
			},
			Steps: []string{
				"Установите клиент",
				"Скопируйте ссылку подписки",
				"Импорт подписки",
				"Разрешите VPN-конфигурацию в Системных настройках",
			},
		},
		{
			Name: "Linux",
			Clients: []osClient{
				{Name: "Hiddify-Next (AppImage)", URL: "https://github.com/hiddify/hiddify-next/releases"},
				{Name: "NekoRay (AppImage)", URL: "https://github.com/MatsuriDayo/nekoray/releases"},
			},
			Steps: []string{
				"Скачайте AppImage клиента, сделайте chmod +x",
				"Запустите и импортируйте подписку",
				"Включите TUN-режим (требует sudo)",
			},
		},
		{
			Name: "Android TV",
			Clients: []osClient{
				{Name: "Happ (Google Play TV)", URL: "https://play.google.com/store/apps/details?id=com.happproxy"},
				{Name: "v2rayNG (apk)", URL: "https://github.com/2dust/v2rayNG/releases"},
			},
			Steps: []string{
				"Установите клиент через Play Market на телевизоре",
				"Подписку добавьте по QR-коду со страницы /subscriptions",
				"Включите подключение",
			},
		},
	}
}

func Info(d InfoData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-6\"><div class=\"flex items-center gap-3\"><a href=\"/\" class=\"flex h-10 w-10 items-center justify-center rounded-xl border border-dark-700 bg-dark-800\"><svg class=\"h-5 w-5\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" stroke-width=\"2\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M15.75 19.5L8.25 12l7.5-7.5\"></path></svg></a><h1 class=\"text-2xl font-bold text-dark-50 sm:text-3xl\">Как подключиться</h1></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if d.SubURL != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"glass rounded-2xl p-4\"><div class=\"text-xs uppercase tracking-wider text-dark-400\">Ваша ссылка подписки</div><div class=\"mt-2 flex gap-2\"><code id=\"sub-url-info\" class=\"flex-1 overflow-x-auto rounded-xl bg-white/5 px-3 py-2 text-[11px] mono text-dark-50/70 break-all\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(d.SubURL)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `backend_remnawave/web/templates/info.templ`, Line: 115, Col: 146}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</code> <button type=\"button\" onclick=\"navigator.clipboard.writeText(document.getElementById('sub-url-info').innerText); this.innerText='OK'; setTimeout(()=>this.innerText='Копировать',1500)\" class=\"btn-icon\">Копировать</button></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"space-y-4\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, g := range osGuides() {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<details class=\"glass rounded-2xl overflow-hidden\"><summary class=\"cursor-pointer px-5 py-4 flex items-center justify-between hover:bg-white/5\"><span class=\"text-base font-semibold text-dark-100\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(g.Name)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `backend_remnawave/web/templates/info.templ`, Line: 124, Col: 67}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</span> <svg class=\"h-4 w-4 text-dark-400\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M6 9l6 6 6-6\"></path></svg></summary><div class=\"border-t border-dark-700/30 px-5 py-4 space-y-4\"><div><div class=\"mb-2 text-xs uppercase tracking-wider text-dark-400\">Клиенты</div><div class=\"flex flex-wrap gap-2\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				for _, cl := range g.Clients {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<a href=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var5 templ.SafeURL
					templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(cl.URL))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `backend_remnawave/web/templates/info.templ`, Line: 132, Col: 41}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" target=\"_blank\" rel=\"noopener\" class=\"btn-secondary text-xs px-3 py-1.5\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var6 string
					templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(cl.Name)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `backend_remnawave/web/templates/info.templ`, Line: 132, Col: 126}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</a>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div></div><div><div class=\"mb-2 text-xs uppercase tracking-wider text-dark-400\">Шаги</div><ol class=\"list-decimal pl-5 space-y-1 text-sm text-dark-300\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				for _, step := range g.Steps {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<li>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var7 string
					templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(step)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `backend_remnawave/web/templates/info.templ`, Line: 140, Col: 20}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</li>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</ol></div></div></details>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Подключение", "/info", true).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
